export declare const loader_color_first: string
export declare const loader_color_fourth: string
export declare const loader_color_second: string
export declare const loader_color_third: string
export declare const loader_sizeL: string
export declare const loader_sizeM: string
export declare const loader_sizeS: string
export declare const loaderIcon: string
export declare const loaderRoot: string
export declare const rotate: string
