export declare const activityDay: string
export declare const avatar: string
export declare const avatarLarge: string
export declare const avatarRepo: string
export declare const backIcon: string
export declare const branchList: string
export declare const branchProtected: string
export declare const contributors: string
export declare const dayRow: string
export declare const description: string
export declare const header: string
export declare const level0: string
export declare const level1: string
export declare const level2: string
export declare const level3: string
export declare const monthLabel: string
export declare const monthLabels: string
export declare const repoPage: string
export declare const statItem: string
export declare const stats: string
